apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: {{ .Release.Namespace }}
data:
  init-user.js: |
    db = db.getSiblingDB("appdb");
    db.createUser({
      user: "root",
      pwd: "password123",
      roles: [ { role: "readWrite", db: "appdb" } ]
    });
