apiVersion: v1
kind: Service
metadata:
  name: mongo-mongodb
  labels:
    {{- include "mongo-mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mongo-mongodb
  ports:
    - name: mongo-mongodb
      port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
