controller:
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: ClusterIP     # hostPort kullandığımız için Service dışa açılmasın
  ingressClassResource:
    name: nginx
    default: false      # istersen true yapabilirsin
